### ISSUE TITLE
您好，软件已经成功使用非常好用

### ISSUE THREAD

**Issue by wscjxky** [Jesse201147/PhoneBoom#2]
您好，您这个软件特别好，请问能给我私发一下吗，我挺需要的，因为被一个中介骗了1000元押金，一直没给退，现在还在猖獗的继续租房，挺难受的，谢谢，这是我的qq：619677632@qq.com

**Comment by wscjxky** [comment]
更多的一些网站

**Comment by Jesse201147** [comment]
推荐你下一个点验APP 可以点击发送语音验证码, 这个比较烦, 
短信验证码很多手机都可以屏蔽的, 半夜来发语音验证码还是很烦的

**Comment by Jesse201147** [comment]
> 更多的一些网站

推荐你下一个点验APP 可以点击发送语音验证码, 这个比较烦,
短信验证码很多手机都可以屏蔽的, 半夜来发语音验证码还是很烦的

**Comment by wscjxky** [comment]
好的谢谢！
